name: build_docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.5"
      - run: uv python install
      - run: uv sync
      - run: uv run mkdocs gh-deploy --force --clean --verbose
